### ISSUE TITLE
The accursed glyph alignment bug rears its ugly head

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/ScribbleJunior#2] opened 2024-03-04 06:06 UTC
Having never written a text renderer, I have no idea why these are so weirdly common, but the `w` is one pixel lower than it should be. This appears to be the case with any lowercase `w` in the default font. I haven't caught it happening with any other letters, including capital `W`.

![image](https://github.com/JujuAdams/ScribbleJunior/assets/7087495/63a90c27-1ba3-4811-8675-c7b9d4b656c1)

**Comment by JujuAdams** [comment] 2024-03-04 10:06
Unable to reproduce - could you share some further details?

**Comment by DragoniteSpam** [comment] 2024-03-04 21:33
Usually when I see this it's because I'm trying to draw text at fractional coordinates, but not in this case. I also looked at the vertex buffer itself and it doesn't appear that there are any off-by-ones in the quads for any of the glyphs, which makes me think the font_get_uvs() texture coordinates might be wrong under certain conditions.

[test - scribble jr.zip](https://github.com/JujuAdams/ScribbleJunior/files/14487339/test.-.scribble.jr.zip)

**Comment by JujuAdams** [comment] 2024-03-04 23:00
tyvm will take a look soon

**Comment by JujuAdams** [comment] 2024-03-08 19:54
That project doesn't reproduce the issue for me. So that's a thing.

**Comment by DragoniteSpam** [comment] 2024-03-12 17:05
oh exciting. usually when that happens it's because of some GPU-specific nonsense (nvidia here). what GPU are you running on?

**Comment by JujuAdams** [comment] 2024-03-12 19:21
GTX 1070

**Comment by DragoniteSpam** [comment] 2024-03-12 21:38
that's pretty similar to mine (1060), wouldn't expect that to cause any differences. wait for someone else to come by with the problem, i suppose?

**Comment by JujuAdams** [comment] 2024-03-13 13:43
Yep!

**Comment by tabularelf** [comment] 2024-03-14 20:41
I decided to check out the `test - scribble jr.zip` myself, and well it looks like I'm getting the same issue.
GPU: GTX 1080
Driver version: 546.17 (November/14/2023)
<img width="798" alt="2024-03-15_07-39-38" src="https://github.com/JujuAdams/ScribbleJunior/assets/26135221/be87c2e4-f5b6-4025-9abc-fb922c90da59">

**Comment by KormexGit** [comment] 2024-03-14 20:49
![image](https://github.com/JujuAdams/ScribbleJunior/assets/100942509/aa4b952e-7174-4750-ba69-52656089a4e3)
Also happening for me

![image](https://github.com/JujuAdams/ScribbleJunior/assets/100942509/c7032b9d-ba79-42c4-a81f-03e1224ef018)

Edit: Changed font to Arial size 24, as well as enabling a 1920x1080 viewport, and the capital K is visibly a pixel too high, added lines to try to make it easier to see. The lower case o, e, and t also appear to be a pixel high
![image](https://github.com/JujuAdams/ScribbleJunior/assets/100942509/5b13c00d-8f5e-44d0-be10-854633cf8b64)

I've run into text misalignment with HD resolution before, and enabling color interpolation fixes it
![image](https://github.com/JujuAdams/ScribbleJunior/assets/100942509/b658c355-a312-4fa7-ab02-9b03cd70ea4d)

Though drawing the text with no interpolation with regular draw_text doesn't have the misalignment 
![image](https://github.com/JujuAdams/ScribbleJunior/assets/100942509/e31c26ad-1516-4ea7-8fbb-70c81ee6b608)
Can see in that screenshot above that the ``d`` and ``p`` lost a pixel on the right side, ``g`` lost a pixel on the bottom, ``n`` , ``o``, and ``w`` and ``m`` have one more pixel on the left in the scribble JR version compared to the draw text version 

Here's my slightly edited test project
[test - scribble jr2.zip](https://github.com/JujuAdams/ScribbleJunior/files/14607946/test.-.scribble.jr2.zip)

**Comment by JujuAdams** [comment] 2024-03-16 19:15
Think I've identified the issue: there's some loss of accuracy in texture UVs which is causing the texture to be slightly misaligned. I think I have a fixed now and I'm working on porting that solution over. I further believe this issue to affect all vertex buffer bakers, not formatting-enabled versions.

**Comment by JujuAdams** [comment] 2024-03-16 21:45
https://github.com/JujuAdams/ScribbleJunior/commit/b3d80bbcd5e08fb6c77cca03fb2f4d2f9a730479

**Closed as completed by JujuAdams** 2024-03-16 21:45 UTC
Labels: bug :sweat_smile:
